In [3]:
import numpy as np


In [4]:
#create special arrays

print(np.zeros(3))
print (np.zeros([3,6]))


print(np.ones([3,6]))


[ 0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]


In [6]:
print(np.linspace(100,200,3))

[ 100.  150.  200.]


In [7]:
np.logspace(0,3,4)

array([    1.,    10.,   100.,  1000.])

In [8]:
int_array = np.arange(5)

In [10]:
int_array.astype(float)


array([ 0.,  1.,  2.,  3.,  4.])

In [24]:
data1 = [1,2,3,4,5.0]

arr1 = np.array(data1)


print(arr1.dtype)



data2 = [range(1,10),range(11,20)]

arr2 = np.array(data2)

print(arr2.dtype)


print(arr2.ndim)



print(arr1.ndim
     )


arr2.shape

arr2.size
arr2.resize(50)

arr2.reshape(10,5)

print(arr2)

float64
int64
2
1
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]


In [26]:
arr3 = np.arange(50, dtype=float)

In [33]:
dataarr3.reshape((2,5,5))

array([[[  0.,   1.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.,   9.],
        [ 10.,  11.,  12.,  13.,  14.],
        [ 15.,  16.,  17.,  18.,  19.],
        [ 20.,  21.,  22.,  23.,  24.]],

       [[ 25.,  26.,  27.,  28.,  29.],
        [ 30.,  31.,  32.,  33.,  34.],
        [ 35.,  36.,  37.,  38.,  39.],
        [ 40.,  41.,  42.,  43.,  44.],
        [ 45.,  46.,  47.,  48.,  49.]]])

In [44]:
data = range(1,7)
array = np.array(data)
matrix1 = array
matrix1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
print(matrix1)

[1 2 3 4 5]


In [53]:
mat = np.matrix('1,2,3;4,5,6')
mat2 = np.matrix('2;2;2')
mat * mat2

matrix([[12],
        [30]])