In [1]:
import numpy as np


In [6]:
#create special arrays

print(np.zeros(3))
print (np.zeros([3,6]))


print(np.ones([3,6]))


[ 0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]


In [13]:
print(np.linspace(100,200,401))

[ 100.    100.25  100.5   100.75  101.    101.25  101.5   101.75  102.
  102.25  102.5   102.75  103.    103.25  103.5   103.75  104.    104.25
  104.5   104.75  105.    105.25  105.5   105.75  106.    106.25  106.5
  106.75  107.    107.25  107.5   107.75  108.    108.25  108.5   108.75
  109.    109.25  109.5   109.75  110.    110.25  110.5   110.75  111.
  111.25  111.5   111.75  112.    112.25  112.5   112.75  113.    113.25
  113.5   113.75  114.    114.25  114.5   114.75  115.    115.25  115.5
  115.75  116.    116.25  116.5   116.75  117.    117.25  117.5   117.75
  118.    118.25  118.5   118.75  119.    119.25  119.5   119.75  120.
  120.25  120.5   120.75  121.    121.25  121.5   121.75  122.    122.25
  122.5   122.75  123.    123.25  123.5   123.75  124.    124.25  124.5
  124.75  125.    125.25  125.5   125.75  126.    126.25  126.5   126.75
  127.    127.25  127.5   127.75  128.    128.25  128.5   128.75  129.
  129.25  129.5   129.75  130.    130.25  130.5   130.75  131.