In [1]:
%config IPCompleter.greedy=True

In [2]:
def BlockType(s):
    s = s.strip().lower()
    if s == "irregular":
        return 1
    if s == "regular":
        return 2
    if s == "corner":
        return 3
    return 0
def Storey(s):
    s = s.strip().lower()
    if s == "single":
        return 1
    if s == "double":
        return 2
    return 0

In [3]:
import pandas as pd
import numpy as np
import scipy.stats as ss
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [4]:
data1 = pd.read_csv('BDataFile.csv',encoding='utf8',converters={"BlockType":BlockType,"Storey":Storey})
test = pd.read_csv('BTest.csv',encoding='utf8',converters={"BlockType":BlockType,"Storey":Storey})

data3 = pd.merge(test,data1,how='outer')
data3.iloc[0:,4:]

Storey  CarSpaces    Price  Study  Ensuite  BedRooms  BathRooms  \
0          2          2   397139      1        1         3          2   
1          1          2   397139      0        1         4          2   
2          1          2   731295      0        1         4          2   
3          1          2   738395      0        1         4          2   
4          2          2   853595      1        1         5          2   
5          2          2   849395      1        1         4          2   
6          1          2   587835      1        1         4          2   
7          1          2   399155      0        1         4          2   
8          1          2   404805      0        1         4          2   
9          1          2   360115      0        1         3          2   
10         1          2   394255      0        1         4          2   
11         1          2   393565      0        1         4          2   
12         1          1   359335      0        1         3          2   
13         1          2   391255      0        1         4          2   
14         2          2   507945      1        1         4          2   
15         2          2   494535      1        1         4          2   
16         2          2   458725      1        1         3          2   
17         2          2   529745      1        1         4          2   
18         2          2   473795      1        1         4          2   
19         1          2   673512      0        1         3          2   
20         1          2   386459      0        1         4          2   
21         1          2   755625      1        1         4          2   
22         1          2   755825      0        1         4          2   
23         1          2  1086400      1        1         4          2   
24         1          2  1059309      0        1         4          2   
25         1          2  1062409      0        1         4          2   
26         2          2  1176806      1        1         4          2   
27         1          2   756612      1        1         4          2   
28         1          2   438765      0        1         4          2   
29         1          2   424955      0        1         4          2   
...      ...        ...      ...    ...      ...       ...        ...   
3414       1          2   539950      0        1         3          2   
3415       1          2   514999      0        1         4          2   
3416       1          2   532270      0        1         3          2   
3417       1          2   577330      0        1         4          2   
3418       1          2   584530      1        1         4          2   
3419       1          2   596127      0        1         4          2   
3420       1          2   593080      0        1         3          2   
3421       1          2   596347      0        1         4          2   
3422       2          2   542447      1        1         4          2   
3423       2          2   589550      1        1         4          2   
3424       2          2   623600      1        1         4          2   
3425       2          2   571130      1        1         3          2   
3426       1          2   467500      0        1         3          2   
3427       1          2   549860      0        1         4          2   
3428       1          2   494520      0        1         4          2   
3429       1          2   529920      0        1         3          2   
3430       1          2   457730      0        1         3          2   
3431       2          1   455400      1        1         3          2   
3432       1          2   505280      0        1         4          2   
3433       1          2   496620      0        1         4          2   
3434       1          2   494607      0        1         3          2   
3435       2          1   557287      1        1         3          2   
3436       1          2   677557      0        1         4      

In [12]:
#ata = pd.read_csv('BDataFile.csv',encoding='utf8')
#data = pd.read_csv('BDataFile.csv',encoding='utf8',converters={"BlockType":BlockType,"Storey":Storey})

#storey = set(data['Storey'])
#data


df = pd.DataFrame(data3, columns=['Storey', 'CarSpaces', 'Price', 'Study', 'Ensuite','BedRooms','LandSize','BlockType','HouseSize']).astype('float64')

sc_X = StandardScaler()
dfx = sc_X.fit_transform(df)
dfx



array([[ 1.61674086,  0.25611337, -1.43515636, ..., -0.00422374,
        -0.21656354,  0.26987115],
       [-0.61852832,  0.25611337, -1.43515636, ...,  0.00446502,
        -2.1844919 ,  0.14841789],
       [-0.61852832,  0.25611337,  1.00706745, ..., -0.01907362,
        -2.1844919 , -0.35257679],
       ...,
       [-0.61852832, -3.90452084, -0.43907729, ..., -0.04671967,
        -0.21656354, -0.86875314],
       [ 1.61674086,  0.25611337,  0.06426831, ..., -0.04671967,
        -0.21656354, -0.39812177],
       [-0.61852832, -3.90452084, -0.61667709, ..., -0.04671967,
        -0.21656354, -1.68856262]])

In [6]:
num_cols = len(df[0,:])
for i in range(num_cols):
    col = df[:,i]
    col_stats = ss.describe(col)
    print(col_stats)

DescribeResult(nobs=3444, minmax=(-0.6185283164104337, 1.6167408564306298), mean=-4.848360711487327e-17, variance=1.0002904443799014, skewness=0.9982125400201958, kurtosis=-1.003571724946429)
DescribeResult(nobs=3444, minmax=(-3.9045208436974597, 0.25611337217322416), mean=-2.1869201507134327e-16, variance=1.0002904443799012, skewness=-3.6484074715242354, kurtosis=11.310877078273865)
DescribeResult(nobs=3444, minmax=(-2.2762997109622165, 16.730167723045113), mean=-2.310708083772684e-16, variance=1.0002904443799012, skewness=2.8146913524444153, kurtosis=35.19737838739842)
DescribeResult(nobs=3444, minmax=(-0.7261354744623948, 1.3771534860493695), mean=-8.252528870616727e-18, variance=1.0002904443799012, skewness=0.6510180115869748, kurtosis=-1.576175548589342)
DescribeResult(nobs=3444, minmax=(0.0, 0.0), mean=0.0, variance=0.0, skewness=0.0, kurtosis=-3.0)
DescribeResult(nobs=3444, minmax=(-3.2402447970307513, 2.2452884231759866), mean=-8.252528870616727e-17, variance=1.000290444379901,

In [29]:
neigh = KNeighborsClassifier(n_neighbors=2)
neigh.fit(data1.iloc[0:,4:], data1['Packageid'])
print(neigh.predict(test.iloc[0:,4:]))
print(neigh.kneighbors(test.iloc[0:,4:])[1])

[189951]
[[  0 515]]


In [31]:
neigh = KNeighborsClassifier(n_neighbors=2)
neigh.fit(dfx[1:,4:], data1['Packageid'])
print(neigh.predict(dfx[0:1,4:]))
print(neigh.kneighbors(dfx[0:1,4:])[1])

results = neigh.kneighbors(dfx[0:1,4:])[1]
print(results)

[207891]
[[140  60]]
[[140  60]]


In [49]:
data1.loc[140]
data1.loc[550]
data1.loc[0]

Packageid     189951
HouseName    Vermont
Facade       Strider
Brand            Gen
Storey             1
CarSpaces          2
Price         397139
Study              0
Ensuite            1
BedRooms           4
BathRooms          2
LandSize         660
BlockType          1
HouseSize        251
Name: 0, dtype: object

In [43]:
data1.index.tolist()

AttributeError: 'list' object has no attribute 'items'